[http]
  [http.routers]
    [http.routers.food-service-local]
      rule = "PathPrefix(`/api/food`)"
      service = "food-service-local"
      middlewares = ["food-strip"]
    [http.routers.order-service-local]
      rule = "PathPrefix(`/api/order`)"
      service = "order-service-local"
      middlewares = ["order-strip"]
    [http.routers.user-service-local]
      rule = "PathPrefix(`/api/user`)"
      service = "user-service-local"
      middlewares = ["user-strip"]
    [http.routers.payment-service-local]
      rule = "PathPrefix(`/api/payment`)"
      service = "payment-service-local"
      middlewares = ["payment-strip"]

  [http.middlewares]
    [http.middlewares.food-strip.stripPrefix]
      prefixes = ["/api/food"]
    [http.middlewares.user-strip.stripPrefix]
      prefixes = ["/api/user"]
    [http.middlewares.order-strip.stripPrefix]
      prefixes = ["/api/order"]
    [http.middlewares.payment-strip.stripPrefix]
      prefixes = ["/api/payment"]

  [http.services]
    [http.services.food-service-local]
      [http.services.food-service-local.loadBalancer]
        [[http.services.food-service-local.loadBalancer.servers]]
          url = "http://food-service:8082"
    [http.services.user-service-local]
      [http.services.user-service-local.loadBalancer]
        [[http.services.user-service-local.loadBalancer.servers]]
          url = "http://user-service:8081"
    [http.services.order-service-local]
      [http.services.order-service-local.loadBalancer]
        [[http.services.order-service-local.loadBalancer.servers]]
          url = "http://order-service:8083"
    [http.services.payment-service-local]
      [http.services.payment-service-local.loadBalancer]
        [[http.services.payment-service-local.loadBalancer.servers]]
          url = "http://payment-service:8084"
