[http]
  [http.routers]
    [http.routers.food-service-local]
      rule = "PathPrefix(`/api/food`)"
      service = "food-service-local"
      middlewares = ["food-strip"]
    [http.routers.user-service-local]
      rule = "PathPrefix(`/api/user`)"
      service = "user-service-local"
      middlewares = ["user-strip"]

  [http.middlewares]
    [http.middlewares.food-strip.stripPrefix]
      prefixes = ["/api/food"]
    [http.middlewares.user-strip.stripPrefix]
      prefixes = ["/api/user"]

  [http.services]
    [http.services.food-service-local]
      [http.services.food-service-local.loadBalancer]
        [[http.services.food-service-local.loadBalancer.servers]]
          url = "http://host.docker.internal:8082"
    [http.services.user-service-local]
      [http.services.user-service-local.loadBalancer]
        [[http.services.user-service-local.loadBalancer.servers]]
          url = "http://user-service:8081"
